"""image-url-revision

Revision ID: 8a4759609c00
Revises: d9412d6dffe4
Create Date: 2025-04-22 16:20:57.597146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a4759609c00'
down_revision = 'd9412d6dffe4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Product', sa.Column('image_url', sa.String(), nullable=True, comment='Ссылка на изображение товара'), schema='inventory')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Product', 'image_url', schema='inventory')
    # ### end Alembic commands ###