"""order-payment-revision

Revision ID: 00af64c2d488
Revises: 026b7c1bd964
Create Date: 2025-05-10 20:52:33.582487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00af64c2d488'
down_revision = '026b7c1bd964'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('payment_id', sa.String(length=255), nullable=True, comment='Идентификатор платежа'), schema='order')
    op.add_column('orders', sa.Column('payment_status', sa.String(length=255), nullable=True, comment='Статус платежа'), schema='order')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'payment_status', schema='order')
    op.drop_column('orders', 'payment_id', schema='order')
    # ### end Alembic commands ###