"""employee-revision

Revision ID: a3c494e69d8b
Revises: 558acfbee2e0
Create Date: 2025-04-22 12:23:56.366213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3c494e69d8b'
down_revision = '558acfbee2e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'employee_id',
               existing_type=sa.UUID(),
               nullable=True,
               existing_comment='Идентификатор сотрудника',
               schema='order')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'employee_id',
               existing_type=sa.UUID(),
               nullable=False,
               existing_comment='Идентификатор сотрудника',
               schema='order')
    # ### end Alembic commands ###