"""comment-revision

Revision ID: 167c65a3e231
Revises: 83df6301cf82
Create Date: 2025-05-09 14:08:53.787506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '167c65a3e231'
down_revision = '83df6301cf82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('comment', sa.String(length=255), nullable=True, comment='Комментарий к заказу'), schema='order')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'comment', schema='order')
    # ### end Alembic commands ###