"""order-number-revision

Revision ID: 026b7c1bd964
Revises: 167c65a3e231
Create Date: 2025-05-09 14:23:08.868811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '026b7c1bd964'
down_revision = '167c65a3e231'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_number', sa.String(length=127), nullable=False, comment='Номер заказа'), schema='order')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'order_number', schema='order')
    # ### end Alembic commands ###