"""new3-revision

Revision ID: 83df6301cf82
Revises: 74f152bfe7df
Create Date: 2025-04-26 22:26:50.420102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83df6301cf82'
down_revision = '74f152bfe7df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('telegram_user_id', sa.Integer(), nullable=True, comment='Telegram user id'),
    sa.Column('contact_person', sa.String(), nullable=True, comment='Контактное лицо'),
    sa.Column('address', sa.Text(), nullable=True, comment='Адрес'),
    sa.Column('city', sa.String(), nullable=True, comment='Город'),
    sa.Column('region', sa.String(), nullable=True, comment='Регион'),
    sa.Column('postal_code', sa.String(), nullable=True, comment='Почтовый индекс'),
    sa.Column('country', sa.String(), nullable=True, comment='Страна'),
    sa.Column('phone_number', sa.String(), nullable=True, comment='Телефон'),
    sa.Column('email', sa.String(), nullable=True, comment='Электронная почта'),
    sa.Column('inn', sa.String(), nullable=True, comment='ИНН'),
    sa.Column('id', sa.UUID(), nullable=False, comment='ID'),
    sa.Column('ts_create', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания записи'),
    sa.Column('ts_modify', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Дата и время обновления'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Флаг, что запись удалена'),
    sa.Column('_trigger_off', sa.Boolean(), server_default=sa.text('NULL'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='customer'
    )
    op.create_table('employees',
    sa.Column('first_name', sa.String(), nullable=False, comment='Имя сотрудника'),
    sa.Column('last_name', sa.String(), nullable=False, comment='Фамилия сотрудника'),
    sa.Column('position', sa.String(), nullable=False, comment='Должность сотрудника'),
    sa.Column('phone_number', sa.String(), nullable=False, comment='Телефон сотрудника'),
    sa.Column('email', sa.String(), nullable=False, comment='Электронная почта сотрудника'),
    sa.Column('id', sa.UUID(), nullable=False, comment='ID'),
    sa.Column('ts_create', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания записи'),
    sa.Column('ts_modify', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Дата и время обновления'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Флаг, что запись удалена'),
    sa.Column('_trigger_off', sa.Boolean(), server_default=sa.text('NULL'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='employee'
    )
    op.create_table('categories',
    sa.Column('name', sa.String(), nullable=False, comment='Наименование категории'),
    sa.Column('description', sa.Text(), nullable=True, comment='Описание категории'),
    sa.Column('id', sa.UUID(), nullable=False, comment='ID'),
    sa.Column('ts_create', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания записи'),
    sa.Column('ts_modify', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Дата и время обновления'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Флаг, что запись удалена'),
    sa.Column('_trigger_off', sa.Boolean(), server_default=sa.text('NULL'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='inventory'
    )
    op.create_table('warehouses',
    sa.Column('name', sa.String(), nullable=False, comment='Название склада'),
    sa.Column('address', sa.Text(), nullable=False, comment='Адрес склада'),
    sa.Column('id', sa.UUID(), nullable=False, comment='ID'),
    sa.Column('ts_create', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания записи'),
    sa.Column('ts_modify', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Дата и время обновления'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Флаг, что запись удалена'),
    sa.Column('_trigger_off', sa.Boolean(), server_default=sa.text('NULL'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='inventory'
    )
    op.create_table('status',
    sa.Column('name', sa.String(), nullable=False, comment='Наименование статуса'),
    sa.Column('description', sa.Text(), nullable=True, comment='Описание статуса'),
    sa.Column('id', sa.UUID(), nullable=False, comment='ID'),
    sa.Column('ts_create', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания записи'),
    sa.Column('ts_modify', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Дата и время обновления'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Флаг, что запись удалена'),
    sa.Column('_trigger_off', sa.Boolean(), server_default=sa.text('NULL'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='order'
    )
    op.create_table('suppliers',
    sa.Column('company_name', sa.String(), nullable=False, comment='Наименование компании'),
    sa.Column('contact_person', sa.String(), nullable=False, comment='Контактное лицо'),
    sa.Column('address', sa.Text(), nullable=False, comment='Адрес'),
    sa.Column('city', sa.String(), nullable=False, comment='Город'),
    sa.Column('region', sa.String(), nullable=False, comment='Регион'),
    sa.Column('postal_code', sa.String(), nullable=False, comment='Почтовый индекс'),
    sa.Column('phone_number', sa.String(), nullable=False, comment='Телефон'),
    sa.Column('email', sa.String(), nullable=False, comment='Электронная почта'),
    sa.Column('id', sa.UUID(), nullable=False, comment='ID'),
    sa.Column('ts_create', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания записи'),
    sa.Column('ts_modify', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Дата и время обновления'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Флаг, что запись удалена'),
    sa.Column('_trigger_off', sa.Boolean(), server_default=sa.text('NULL'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='supplier'
    )
    op.create_table('items',
    sa.Column('name', sa.String(), nullable=False, comment='Название объекта'),
    sa.Column('alias', sa.String(), nullable=False, comment='Алиас объекта'),
    sa.Column('id', sa.UUID(), nullable=False, comment='ID'),
    sa.Column('ts_create', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания записи'),
    sa.Column('ts_modify', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Дата и время обновления'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Флаг, что запись удалена'),
    sa.Column('_trigger_off', sa.Boolean(), server_default=sa.text('NULL'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='user'
    )
    op.create_table('arrivals',
    sa.Column('supplier_id', sa.UUID(), nullable=False, comment='Идентификатор поставщика'),
    sa.Column('warehouse_id', sa.UUID(), nullable=False, comment='Идентификатор склада'),
    sa.Column('arrival_date', sa.Date(), nullable=False, comment='Дата поступления'),
    sa.Column('id', sa.UUID(), nullable=False, comment='ID'),
    sa.Column('ts_create', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания записи'),
    sa.Column('ts_modify', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Дата и время обновления'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Флаг, что запись удалена'),
    sa.Column('_trigger_off', sa.Boolean(), server_default=sa.text('NULL'), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.suppliers.id'], name='suppliers_supplier_id_fkey', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['inventory.warehouses.id'], name='inventory_warehouse_id_fkey', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='inventory'
    )
    op.create_table('product',
    sa.Column('category_id', sa.UUID(), nullable=False, comment='Идентификатор категории'),
    sa.Column('warehouse_id', sa.UUID(), nullable=False, comment='Идентификатор склада'),
    sa.Column('arrival_id', sa.UUID(), nullable=False, comment='Идентификатор поступления'),
    sa.Column('name', sa.String(), nullable=False, comment='Наименование товара'),
    sa.Column('description', sa.String(), nullable=True, comment='Описание товара'),
    sa.Column('image_url', sa.String(), nullable=True, comment='Ссылка на изображение товара'),
    sa.Column('unit_of_measure', sa.String(), nullable=False, comment='Единица измерения товара'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='Количество товара'),
    sa.Column('article_number', sa.String(), nullable=False, comment='Артикул товара'),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False, comment='Цена товара'),
    sa.Column('id', sa.UUID(), nullable=False, comment='ID'),
    sa.Column('ts_create', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания записи'),
    sa.Column('ts_modify', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Дата и время обновления'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Флаг, что запись удалена'),
    sa.Column('_trigger_off', sa.Boolean(), server_default=sa.text('NULL'), nullable=True),
    sa.ForeignKeyConstraint(['arrival_id'], ['inventory.arrivals.id'], name='inventory_arrival_id_fkey', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['category_id'], ['inventory.categories.id'], name='inventory_category_id_fkey', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['inventory.warehouses.id'], name='inventory_warehouse_id_fkey', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='inventory'
    )
    op.create_table('orders',
    sa.Column('customer_id', sa.UUID(), nullable=False, comment='Идентификатор заказчика'),
    sa.Column('product_id', sa.UUID(), nullable=False, comment='Идентификатор номенклатуры'),
    sa.Column('employee_id', sa.UUID(), nullable=True, comment='Идентификатор сотрудника'),
    sa.Column('order_status_id', sa.UUID(), nullable=False, comment='Статус заказа'),
    sa.Column('address', sa.String(length=255), nullable=False, comment='Адрес доставки'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='Количество'),
    sa.Column('order_date', sa.Date(), nullable=False, comment='Дата заказа'),
    sa.Column('actual_delivery_date', sa.Date(), nullable=True, comment='Фактическая дата отгрузки'),
    sa.Column('id', sa.UUID(), nullable=False, comment='ID'),
    sa.Column('ts_create', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания записи'),
    sa.Column('ts_modify', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Дата и время обновления'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Флаг, что запись удалена'),
    sa.Column('_trigger_off', sa.Boolean(), server_default=sa.text('NULL'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customers.id'], name='customers_customer_id_fkey', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.employees.id'], name='employee_employees_id_fkey', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_status_id'], ['order.status.id'], name='order_status_id_fkey', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['inventory.product.id'], name='inventory_product_id_fkey', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='order'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders', schema='order')
    op.drop_table('product', schema='inventory')
    op.drop_table('arrivals', schema='inventory')
    op.drop_table('items', schema='user')
    op.drop_table('suppliers', schema='supplier')
    op.drop_table('status', schema='order')
    op.drop_table('warehouses', schema='inventory')
    op.drop_table('categories', schema='inventory')
    op.drop_table('employees', schema='employee')
    op.drop_table('customers', schema='customer')
    # ### end Alembic commands ###